// This file is auto-generated by @hey-api/openapi-ts

export type AccessTokenResponse = {
    readonly tokenType?: string | null;
    accessToken: string | null;
    expiresIn: number;
    refreshToken: string | null;
};

export type AccountInvite = {
    id?: number;
    guid?: string;
    organizationId?: string | null;
    organization?: Organization;
    userId?: string | null;
    user?: ApplicationUser;
    email?: string | null;
    isUsed?: boolean;
    createdOn?: string;
};

export type ApplicationUser = {
    organizationId?: string | null;
    personId?: number | null;
    person?: Person;
    readonly readableName?: string | null;
    readonly sortableName?: string | null;
    email?: string | null;
    emailConfirmed?: boolean;
    passwordHash?: string | null;
    securityStamp?: string | null;
    phoneNumber?: string | null;
    phoneNumberConfirmed?: boolean;
    twoFactorEnabled?: boolean;
    lockoutEnabled?: boolean;
    accessFailedCount?: number;
    id?: string;
    userName?: string | null;
    normalizedUserName?: string | null;
    normalizedEmail?: string | null;
    concurrencyStamp?: string | null;
    lockoutEnd?: string | null;
};

export type AvaiableModule = {
    id?: number;
    organizationId?: string;
    organization?: Organization;
    moduleId?: number;
    module?: Module;
};

export type BondAcquisitionType = {
    id?: number;
    code?: string | null;
    name?: string | null;
    organizationId?: string;
    organization?: Organization;
};

export type BondProvisionSplit = {
    id?: number;
    code?: string | null;
    name?: string | null;
    company?: number;
    broker?: number;
    tipper?: number;
    isDefault?: boolean;
    organizationId?: string;
    organization?: Organization;
};

export type BondState = {
    id?: number;
    code?: string | null;
    name?: string | null;
    organizationId?: string | null;
};

export type BondType = {
    id?: number;
    code?: string | null;
    name?: string | null;
    organizationId?: string | null;
};

export type Contract = {
    id?: number;
    name?: string | null;
    number?: string | null;
    customerId?: number;
    customer?: Customer;
    contractTypeId?: number | null;
    contractType?: ContractType;
    note?: string | null;
    createdOn?: string;
    files?: Array<File> | null;
    ownerId?: string | null;
    owner?: ApplicationUser;
    tasks?: Array<Task> | null;
    workplaces?: Array<Workplace> | null;
    contractState?: ContractState;
    contractStateId?: number | null;
    contractItems?: Array<ContractItem> | null;
    description?: string | null;
    finishOn?: string | null;
    scheduledFinishOn?: string | null;
    startedOn?: string | null;
    updatedOn?: string | null;
    responsibleUserId?: string | null;
    responsibleUser?: ApplicationUser;
};

export type ContractItem = {
    id?: number;
    name?: string | null;
    contract?: Contract;
    contractId?: number;
    note?: string | null;
    description?: string | null;
    price?: number | null;
    quantity?: number | null;
    unitTypeId?: number | null;
    unitType?: UnitType;
    currencyId?: number | null;
    currency?: Currency;
    taxVatId?: number | null;
    taxVat?: TaxVat;
};

export type ContractState = {
    id?: number;
    code?: string | null;
    name?: string | null;
    contracts?: Array<Contract> | null;
    organizationId?: string | null;
    organization?: Organization;
};

export type ContractType = {
    id?: number;
    code?: string | null;
    name?: string | null;
    contracts?: Array<Contract> | null;
    organizationId?: string | null;
    serieNumberId?: number | null;
    serieNumber?: SerieNumber;
    sharedContractTypeId?: number | null;
    useMask?: boolean;
    sharedContractType?: ContractType;
    organization?: Organization;
    sharedBy?: Array<ContractType> | null;
};

export type Currency = {
    id?: number;
    code?: string | null;
    name?: string | null;
    symbol?: string | null;
};

export type Customer = {
    id?: number;
    name?: string | null;
    email?: string | null;
    phone?: string | null;
    city?: string | null;
    street?: string | null;
    postalCode?: string | null;
    taxIdentification?: string | null;
    identification?: string | null;
    guid?: string | null;
    note?: string | null;
    createdOn?: string;
    isValid?: boolean;
    ownerId?: string | null;
    reponsibleUserId?: string | null;
    people?: Array<Person> | null;
    customerTypeId?: number | null;
    customerType?: CustomerType;
    dataCollectionAgreement?: boolean;
    marketingDataUseAgreement?: boolean;
    isDeleted?: boolean;
    registerInformation?: string | null;
    priceTypeCode?: string | null;
    invoiceDueDays?: number | null;
    blockAfterDueDays?: number | null;
    state?: string | null;
    code?: string | null;
    customerGroupId?: number | null;
    customerGroup?: CustomerGroup;
};

export type CustomerGroup = {
    id?: number;
    code?: string | null;
    name?: string | null;
    customers?: Array<Customer> | null;
    organizationId?: string | null;
    organization?: Organization;
};

export type CustomerType = {
    id?: number;
    code?: string | null;
    name?: string | null;
    customers?: Array<Customer> | null;
    organizationId?: string | null;
    organization?: Organization;
};

export type FastOrder = {
    customerId?: number | null;
    customerName?: string | null;
    customerStreet?: string | null;
    customerCity?: string | null;
    customerPostalCode?: string | null;
    customerState?: string | null;
    fastOrderItems?: Array<FastOrderItem> | null;
    note?: string | null;
    customerCompanyIdentification?: string | null;
    customerTaxIdentification?: string | null;
    externalNumber?: string | null;
    phone?: string | null;
    email?: string | null;
    paymentTypeId?: number | null;
};

export type FastOrderItem = {
    stockProductId?: number;
    name?: string | null;
    quantity?: number;
    lineNumber?: number | null;
    warehousePlaceCode?: string | null;
};

export type File = {
    id?: number;
    createdOn?: string;
    name?: string | null;
    extension?: string | null;
    serverPath?: string | null;
    contractId?: number | null;
    customerId?: number | null;
    organizationLogoId?: number | null;
    organizationStampId?: number | null;
    bondId?: number | null;
    referenceId?: string | null;
    referenceType?: string | null;
};

export type ForgotPasswordRequest = {
    email: string | null;
};

export type HttpValidationProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    errors?: {
        [key: string]: Array<string>;
    } | null;
    [key: string]: unknown | (string | null) | (string | null) | (number | null) | (string | null) | (string | null) | ({
        [key: string]: Array<string>;
    } | null) | undefined;
};

export type InfoRequest = {
    newEmail?: string | null;
    newPassword?: string | null;
    oldPassword?: string | null;
};

export type InfoResponse = {
    email: string | null;
    isEmailConfirmed: boolean;
};

export type LoginRequest = {
    email: string | null;
    password: string | null;
    twoFactorCode?: string | null;
    twoFactorRecoveryCode?: string | null;
};

export type Module = {
    id?: number;
    name?: string | null;
    code?: string | null;
    description?: string | null;
    controllerName?: string | null;
    actionName?: string | null;
    avaiableModules?: Array<AvaiableModule> | null;
};

export type Organization = {
    id?: string;
    name?: string | null;
    applicationName?: string | null;
    stampAndSignatureId?: number | null;
    logo?: File;
    stampAndSignature?: File;
    logoId?: number | null;
    accountNumber?: string | null;
    note?: string | null;
    printStatement?: string | null;
    checkStatement?: string | null;
    createdOn?: string;
    vatPayerText?: string | null;
    expirationDate?: string | null;
    applicationUsers?: Array<ApplicationUser> | null;
    workplaces?: Array<Workplace> | null;
    contractTypes?: Array<ContractType> | null;
    customerTypes?: Array<CustomerType> | null;
    customerGroups?: Array<CustomerGroup> | null;
    taskStates?: Array<TaskState> | null;
    serieNumbers?: Array<SerieNumber> | null;
    settings?: Array<OrganizationSetting> | null;
    accountInvites?: Array<AccountInvite> | null;
    bondStates?: Array<BondState> | null;
    bondAcquisitionTypes?: Array<BondAcquisitionType> | null;
    bondProvisionSplits?: Array<BondProvisionSplit> | null;
    bondTypes?: Array<BondType> | null;
    productTypes?: Array<ProductType> | null;
    paymentCycles?: Array<PaymentCycle> | null;
    paymentTypes?: Array<PaymentType> | null;
    unitTypes?: Array<UnitType> | null;
    avaiableModules?: Array<AvaiableModule> | null;
    contractStates?: Array<ContractState> | null;
    taxVats?: Array<TaxVat> | null;
    vatPayer?: boolean;
    currencies?: Array<Currency> | null;
};

export type OrganizationSetting = {
    id?: number;
    organizationId?: string;
    organization?: Organization;
    key?: string | null;
    value?: string | null;
    name?: string | null;
    description?: string | null;
    valueType?: string | null;
};

export type Pagination = {
    page?: number;
    pageSize?: number;
    totalPages?: number;
    totalItems?: number;
};

export type PaymentCycle = {
    id?: number;
    code?: string | null;
    name?: string | null;
    organizationId?: string | null;
};

export type PaymentType = {
    id?: number;
    code?: string | null;
    name?: string | null;
};

export type Person = {
    id?: number;
    titlePre?: string | null;
    firstName?: string | null;
    middleName?: string | null;
    lastName?: string | null;
    titlePost?: string | null;
    customerId?: number | null;
    createdOn?: string;
    note?: string | null;
    profilePictureId?: number | null;
    profilePicture?: File;
    email?: string | null;
    phone?: string | null;
    birthDate?: string | null;
    city?: string | null;
    street?: string | null;
    postalCode?: string | null;
    state?: string | null;
    readableName?: string | null;
    readonly sortableName?: string | null;
};

export type Product = {
    id?: number;
    name?: string | null;
    productCode?: string | null;
    productGroupId?: number | null;
    productGroup?: ProductGroup;
    ownerId?: string;
    supplierId?: number | null;
    productGroupProductMaps?: Array<ProductGroupProductMap> | null;
    productTypeId?: number | null;
    productType?: ProductType;
    note?: string | null;
    productMetas?: Array<ProductMeta> | null;
    productPrices?: Array<ProductPrice> | null;
    buyPrice?: number | null;
    unitTypeId?: number | null;
    unitType?: UnitType;
};

export type ProductGroup = {
    id?: number;
    name?: string | null;
    code?: string | null;
    ownerId?: string;
    description?: string | null;
    externalCode?: string | null;
    isAvailable?: boolean;
    parentProductGroupId?: number | null;
    image?: string | null;
    slug?: string | null;
    productGroupChilds?: Array<ProductGroup> | null;
    productGroupProductMaps?: Array<ProductGroupProductMap> | null;
    showInTree?: boolean | null;
    createdOn?: string;
    updatedOn?: string | null;
    heurekaCategory?: string | null;
    zboziCategory?: string | null;
};

export type ProductGroupProductMap = {
    id?: number;
    idProduct?: number;
    idProductGroup?: number;
    createdOn?: string;
    product?: Product;
    productGroup?: ProductGroup;
};

export type ProductMeta = {
    code?: string | null;
    value?: string | null;
    id?: number;
    productId?: number;
};

export type ProductPrice = {
    id?: number;
    productId?: number;
    price?: number;
    quantityMin?: number | null;
    quantityMax?: number | null;
    description?: string | null;
    currencyCode?: string | null;
    productPriceTypeCode?: string | null;
    createdOn?: string;
    updatedOn?: string | null;
    customerId?: number | null;
    unitTypeId?: number;
    unitType?: UnitType;
    taxVatId?: number | null;
    taxVat?: TaxVat;
    unitCount?: number | null;
};

export type ProductType = {
    id?: number;
    code?: string | null;
    name?: string | null;
    organizationId?: string | null;
};

export type RefreshRequest = {
    refreshToken: string | null;
};

export type RegisterRequest = {
    email: string | null;
    password: string | null;
};

export type ResendConfirmationEmailRequest = {
    email: string | null;
};

export type ResetPasswordRequest = {
    email: string | null;
    resetCode: string | null;
    newPassword: string | null;
};

export type SerieNumber = {
    id?: number;
    organizationId?: string;
    organization?: Organization;
    createdOn?: string;
    name?: string | null;
    mask?: string | null;
    nextNumber?: string | null;
    contractTypes?: Array<ContractType> | null;
};

export type StockBarCode = {
    id?: string;
    stockProductId?: number;
    amount?: number | null;
    barCode?: string | null;
};

export type StockDocument = {
    id?: string;
    stockDocumentNumber?: string | null;
    orderNumber?: string | null;
    customerId?: number | null;
    customerName?: string | null;
    customerStreet?: string | null;
    customerCity?: string | null;
    customerPostalCode?: string | null;
    customerState?: string | null;
    supplierId?: number | null;
    supplierName?: string | null;
    supplierStreet?: string | null;
    supplierCity?: string | null;
    supplierPostalCode?: string | null;
    supplierState?: string | null;
    issueDate?: string;
    deliveryDate?: string | null;
    expeditionDate?: string | null;
    createdOn?: string;
    cancelledOn?: string | null;
    ownerId?: string;
    stockDocumentItems?: Array<StockDocumentItem> | null;
    note?: string | null;
    customerCompanyIdentification?: string | null;
    customerTaxIdentification?: string | null;
    supplierCompanyIdentification?: string | null;
    supplierTaxIdentification?: string | null;
    externalNumber?: string | null;
    warehousePlaces?: Array<WarehousePlace> | null;
    stockDocumentType?: StockDocumentType;
    stockDocumentTypeId?: string | null;
};

export type StockDocumentItem = {
    id?: string;
    name?: string | null;
    quantity?: number;
    stockPrice?: number | null;
    unit?: string | null;
    stockProductId?: number;
    stockProduct?: StockProduct;
    stockDocumentId?: string;
    stockDocument?: StockDocument;
    externalCode?: string | null;
    lineNumber?: number | null;
    quantityMoved?: number | null;
    orderItemId?: number | null;
};

export type StockDocumentPagedData = {
    data?: Array<StockDocument> | null;
    pagination?: Pagination;
};

export type StockDocumentType = {
    id?: string;
    code?: string | null;
    name?: string | null;
    organizationId?: string | null;
    mask?: string | null;
    nextNumber?: string | null;
    stockDocuments?: Array<StockDocument> | null;
};

export type StockItem = {
    id?: number;
    stockProductId?: number;
    stockProduct?: StockProduct;
    warehousePlaceId?: number;
    warehousePlace?: WarehousePlace;
    value?: number | null;
    price?: number | null;
    note?: string | null;
};

export type StockItemApiModel = {
    id?: number;
    warehousePlaceCode?: string | null;
    warehousePlaceId?: number;
    value?: number | null;
};

export type StockMovement = {
    id?: number;
    sourcePlaceId?: number | null;
    sourcePlace?: WarehousePlace;
    destinationPlaceId?: number | null;
    destinationPlace?: WarehousePlace;
    stockProductId?: number;
    stockProduct?: StockProduct;
    value?: number;
    createdOnUtc?: string;
    movedOnUtc?: string;
    movedBy?: string;
    lineNumber?: number | null;
};

export type StockMovementApiModel = {
    stockDocumentId?: string;
    stockMovements?: Array<StockMovementItemApiModel> | null;
};

export type StockMovementItemApiModel = {
    id?: number;
    stockProductId?: number;
    stockProduct?: StockProduct;
    stockItems?: Array<StockItemApiModel> | null;
    place?: string | null;
    value?: number | null;
    lineNumber?: number | null;
};

export type StockProduct = {
    id?: number;
    name?: string | null;
    partNumber?: string | null;
    code?: string | null;
    width?: number | null;
    height?: number | null;
    depth?: number | null;
    weight?: number | null;
    stockItems?: Array<StockItem> | null;
    stockMovements?: Array<StockMovement> | null;
    stockBarCodes?: Array<StockBarCode> | null;
    ownerId?: string;
    note?: string | null;
    stockDocumentItems?: Array<StockDocumentItem> | null;
    productId?: number | null;
    product?: Product;
};

export type Task = {
    id?: number;
    name: string;
    contractId?: number | null;
    contract?: Contract;
    ownerId?: string;
    owner?: ApplicationUser;
    responsibleUserId?: string | null;
    responsibleUser?: ApplicationUser;
    taskStateId?: number;
    taskState?: TaskState;
    lenght?: number | null;
    plannedLenght?: number | null;
    finishedOn?: string | null;
    scheduledFinishOn?: string | null;
    createdOn?: string;
};

export type TaskState = {
    id?: number;
    name?: string | null;
    code?: string | null;
    tasks?: Array<Task> | null;
    organizationId?: string;
    organization?: Organization;
};

export type TaxVat = {
    id?: number;
    value?: number;
};

export type TwoFactorRequest = {
    enable?: boolean | null;
    twoFactorCode?: string | null;
    resetSharedKey?: boolean;
    resetRecoveryCodes?: boolean;
    forgetMachine?: boolean;
};

export type TwoFactorResponse = {
    sharedKey: string | null;
    recoveryCodesLeft: number;
    recoveryCodes?: Array<string> | null;
    isTwoFactorEnabled: boolean;
    isMachineRemembered: boolean;
};

export type UnitType = {
    id?: number;
    code?: string | null;
    name?: string | null;
};

export type Warehouse = {
    id?: number;
    name?: string | null;
    code?: string | null;
    warehousePlaces?: Array<WarehousePlace> | null;
    organizationId?: string;
    isImport?: boolean;
    isExport?: boolean;
};

export type WarehousePlace = {
    id?: number;
    name?: string | null;
    code?: string | null;
    stockItems?: Array<StockItem> | null;
    stockMovementsFrom?: Array<StockMovement> | null;
    stockMovementsTo?: Array<StockMovement> | null;
    warehouseId?: number;
    warehouse?: Warehouse;
    stockDocumentId?: string | null;
};

export type Workplace = {
    id?: number;
    code?: string | null;
    name?: string | null;
    guid?: string | null;
    organizationId: string;
    organization?: Organization;
    contracts?: Array<Contract> | null;
};

export type GetApiCustomerApiData = {
    body?: never;
    path?: never;
    query?: {
        searchString?: string;
    };
    url: '/api/CustomerApi';
};

export type GetApiCustomerApiResponses = {
    /**
     * OK
     */
    200: Array<Customer>;
};

export type GetApiCustomerApiResponse = GetApiCustomerApiResponses[keyof GetApiCustomerApiResponses];

export type PostApiFastOrderApiData = {
    body?: FastOrder;
    path?: never;
    query?: never;
    url: '/api/FastOrderApi';
};

export type PostApiFastOrderApiResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiFastOrderApiPaymentTypesData = {
    body?: never;
    path?: never;
    query?: {
        searchString?: string;
    };
    url: '/api/FastOrderApi/payment-types';
};

export type GetApiFastOrderApiPaymentTypesResponses = {
    /**
     * OK
     */
    200: Array<PaymentType>;
};

export type GetApiFastOrderApiPaymentTypesResponse = GetApiFastOrderApiPaymentTypesResponses[keyof GetApiFastOrderApiPaymentTypesResponses];

export type GetApiFastOrderApiPaymentTypeByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/FastOrderApi/payment-type/{id}';
};

export type GetApiFastOrderApiPaymentTypeByIdResponses = {
    /**
     * OK
     */
    200: PaymentType;
};

export type GetApiFastOrderApiPaymentTypeByIdResponse = GetApiFastOrderApiPaymentTypeByIdResponses[keyof GetApiFastOrderApiPaymentTypeByIdResponses];

export type GetApiStockDocumentApiData = {
    body?: never;
    path?: never;
    query?: {
        type?: string;
        sortOrder?: string;
        searchString?: string;
        currentFilter?: string;
        page?: number;
    };
    url: '/api/StockDocumentApi';
};

export type GetApiStockDocumentApiResponses = {
    /**
     * OK
     */
    200: StockDocumentPagedData;
};

export type GetApiStockDocumentApiResponse = GetApiStockDocumentApiResponses[keyof GetApiStockDocumentApiResponses];

export type GetApiStockDocumentApiByStockDocumentNumberData = {
    body?: never;
    path: {
        stockDocumentNumber: string;
    };
    query?: never;
    url: '/api/StockDocumentApi/{stockDocumentNumber}';
};

export type GetApiStockDocumentApiByStockDocumentNumberResponses = {
    /**
     * OK
     */
    200: StockDocument;
};

export type GetApiStockDocumentApiByStockDocumentNumberResponse = GetApiStockDocumentApiByStockDocumentNumberResponses[keyof GetApiStockDocumentApiByStockDocumentNumberResponses];

export type GetApiStockMovementApiByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/StockMovementApi/{id}';
};

export type GetApiStockMovementApiByIdResponses = {
    /**
     * OK
     */
    200: StockMovementApiModel;
};

export type GetApiStockMovementApiByIdResponse = GetApiStockMovementApiByIdResponses[keyof GetApiStockMovementApiByIdResponses];

export type PostApiStockMovementApiData = {
    body?: StockMovementApiModel;
    path?: never;
    query?: never;
    url: '/api/StockMovementApi';
};

export type PostApiStockMovementApiResponses = {
    /**
     * OK
     */
    200: StockMovementApiModel;
};

export type PostApiStockMovementApiResponse = PostApiStockMovementApiResponses[keyof PostApiStockMovementApiResponses];

export type PostApiStockMovementApiPrintImportLabelData = {
    body?: never;
    path?: never;
    query?: {
        id?: number;
        count?: number;
    };
    url: '/api/StockMovementApi/PrintImportLabel';
};

export type PostApiStockMovementApiPrintImportLabelResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiStockMovementApiPrintExportLabelData = {
    body?: never;
    path?: never;
    query?: {
        id?: number;
        quantity?: number;
        stockItemId?: number;
    };
    url: '/api/StockMovementApi/PrintExportLabel';
};

export type PostApiStockMovementApiPrintExportLabelResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiStockProductApiData = {
    body?: never;
    path?: never;
    query?: {
        searchString?: string;
    };
    url: '/api/StockProductApi';
};

export type GetApiStockProductApiResponses = {
    /**
     * OK
     */
    200: Array<StockProduct>;
};

export type GetApiStockProductApiResponse = GetApiStockProductApiResponses[keyof GetApiStockProductApiResponses];

export type GetApiStockProductApiByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/StockProductApi/{id}';
};

export type GetApiStockProductApiByIdResponses = {
    /**
     * OK
     */
    200: StockProduct;
};

export type GetApiStockProductApiByIdResponse = GetApiStockProductApiByIdResponses[keyof GetApiStockProductApiByIdResponses];

export type PostRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/register';
};

export type PostRegisterErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostRegisterError = PostRegisterErrors[keyof PostRegisterErrors];

export type PostRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostLoginData = {
    body: LoginRequest;
    path?: never;
    query?: {
        useCookies?: boolean;
        useSessionCookies?: boolean;
    };
    url: '/login';
};

export type PostLoginResponses = {
    /**
     * OK
     */
    200: AccessTokenResponse;
};

export type PostLoginResponse = PostLoginResponses[keyof PostLoginResponses];

export type PostRefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/refresh';
};

export type PostRefreshResponses = {
    /**
     * OK
     */
    200: AccessTokenResponse;
};

export type PostRefreshResponse = PostRefreshResponses[keyof PostRefreshResponses];

export type MapIdentityApiConfirmEmailData = {
    body?: never;
    path?: never;
    query: {
        userId: string;
        code: string;
        changedEmail?: string;
    };
    url: '/confirmEmail';
};

export type MapIdentityApiConfirmEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostResendConfirmationEmailData = {
    body: ResendConfirmationEmailRequest;
    path?: never;
    query?: never;
    url: '/resendConfirmationEmail';
};

export type PostResendConfirmationEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostForgotPasswordData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/forgotPassword';
};

export type PostForgotPasswordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostForgotPasswordError = PostForgotPasswordErrors[keyof PostForgotPasswordErrors];

export type PostForgotPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/resetPassword';
};

export type PostResetPasswordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostResetPasswordError = PostResetPasswordErrors[keyof PostResetPasswordErrors];

export type PostResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostManage2FaData = {
    body: TwoFactorRequest;
    path?: never;
    query?: never;
    url: '/manage/2fa';
};

export type PostManage2FaErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostManage2FaError = PostManage2FaErrors[keyof PostManage2FaErrors];

export type PostManage2FaResponses = {
    /**
     * OK
     */
    200: TwoFactorResponse;
};

export type PostManage2FaResponse = PostManage2FaResponses[keyof PostManage2FaResponses];

export type GetManageInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/manage/info';
};

export type GetManageInfoErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetManageInfoError = GetManageInfoErrors[keyof GetManageInfoErrors];

export type GetManageInfoResponses = {
    /**
     * OK
     */
    200: InfoResponse;
};

export type GetManageInfoResponse = GetManageInfoResponses[keyof GetManageInfoResponses];

export type PostManageInfoData = {
    body: InfoRequest;
    path?: never;
    query?: never;
    url: '/manage/info';
};

export type PostManageInfoErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostManageInfoError = PostManageInfoErrors[keyof PostManageInfoErrors];

export type PostManageInfoResponses = {
    /**
     * OK
     */
    200: InfoResponse;
};

export type PostManageInfoResponse = PostManageInfoResponses[keyof PostManageInfoResponses];

export type GetApiWarehousePlaceApiData = {
    body?: never;
    path?: never;
    query?: {
        searchString?: string;
        allowAll?: boolean;
        stockProductId?: number;
    };
    url: '/api/WarehousePlaceApi';
};

export type GetApiWarehousePlaceApiResponses = {
    /**
     * OK
     */
    200: Array<WarehousePlace>;
};

export type GetApiWarehousePlaceApiResponse = GetApiWarehousePlaceApiResponses[keyof GetApiWarehousePlaceApiResponses];

export type ClientOptions = {
    baseUrl: 'http://138.199.147.236:8080' | (string & {});
};